### ISSUE TITLE
웹 페이지 구성 목록

### ISSUE THREAD

**Issue by wiiiiish** [2022-SMHRD-KDT-IoT-2/27.8Hz#3]
1. 네비게이션 바
- [ ] 회원 가입
- [ ] 로그인(장바구니 아이콘 / 알림 아이콘 / 회원정보 수정 / 로그아웃)
- [ ] 나의 건강 정보(시간별 운전자 상태 수치 그래프)

2. 메인
- [ ] WITH U (제품 소개, 설명 / 구매 페이지로 연계)
- [ ] 건강 뉴스(건강 정보 / 공지사항)
- [ ] 고객 센터(자주하는 질문 / 1:1 질문 / 답변)

3. 로그인
- [ ] ID입력
- [ ] 비밀번호입력

**Comment by pys960** [comment]
수정
